app:
  name: PGK
  version: '@project.version@'
  author: Grzegorz Kawalec
  port: ${PORT:10003}
  time-zone: UTC
  api-prefix: /api
  database:
    p6spy: false
    max-pool-size: 10
  security:
    unauthorized-requests: ${app.api-prefix}/info/basic
  mail:
    host: smtp.gmail.com
    port: 587
    login: gkawalecPGK@gmail.com
    password: pgk_gk91

# --------------------------------------------------------------

server:
  port: ${app.port}

spring:
  profiles:
    active: @activatedProfile@
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
    show-sql: false
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
    schemas: pgk
    table: _flyway_schema_history
    validate-on-migrate: true
    baseline-on-migrate: true
    enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: ${app.mail.host}
    port: ${app.mail.port}
    username: ${app.mail.login}
    password: ${app.mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
