export enum LocalStorageKey {

  LANG = 'LANG',

  DASHBOARD_LAST_VISIBLE_PROJECT_ID = 'DASHBOARD_LAST_VISIBLE_PROJECT_ID',

  LEGAL_ACTS_PER_PAGE = 'LEGAL_ACTS_PER_PAGE',
  PROJECTS_PER_PAGE = 'PROJECTS_PER_PAGE',
  ROLES_ITEM_PER_PAGE = 'ROLES_ITEM_PER_PAGE',
  USERS_ITEM_PER_PAGE = 'USERS_ITEM_PER_PAGE'

}

