package pl.gkawalec.pgk.common.type;

/**
 * These enum values are related to the dictionary (front-end) values (they are the keys).
 */

public enum ResponseExceptionType {

    // --- common ---
    ACCESS_DENIED,
    DATA_WAS_UPDATED_EARLIER,
    UNEXPECTED,


    EMPTY_DATA,


    // --- legal act ---
    LEGAL_ACT_BLANK_NAME,
    LEGAL_ACT_BLANK_DATE_OF,
    LEGAL_ACT_BLANK_ID,
    LEGAL_ACT_BLANK_LINK,
    LEGAL_ACT_LINK_EXISTS,
    LEGAL_ACT_NAME_WITH_DATE_OF_EXISTS,
    LEGAL_ACT_NOT_FOUND,

    // --- project ---
    PROJECT_BLANK_NAME,
    PROJECT_BLANK_DATE_END,
    PROJECT_BLANK_DATE_START,
    PROJECT_BLANK_DESCRIPTION,
    PROJECT_BLANK_ID,
    PROJECT_BLANK_LEGAL_ACTS,
    PROJECT_BLANK_PARTICIPANTS,
    PROJECT_BLANK_PROJECT_MANAGER,
    PROJECT_DATE_START_IS_BEFORE_END,
    PROJECT_INCORRECT_LEGAL_ACTS,
    PROJECT_INCORRECT_PARTICIPANTS,
    PROJECT_INCORRECT_PROJECT_MANAGER,
    PROJECT_NOT_FOUND,

    // --- role  ---
    ROLE_BLANK_ID,
    ROLE_BLANK_NAME,
    ROLE_CANNOT_DELETE_ADMIN,
    ROLE_CANNOT_DELETE_GUEST,
    ROLE_CANNOT_UPDATE_ADMIN,
    ROLE_CANNOT_UPDATE_GUEST,
    ROLE_EMPTY_AUTHORITIES,
    ROLE_NAME_EXISTS,
    ROLE_NOT_FOUND,
    ROLE_SET_ADMIN_AUTHORITY,
    ROLE_SET_GUEST_AUTHORITY,

    // --- user ---
    USER_BLANK_EMAIL,
    USER_BLANK_FIRST_NAME,
    USER_BLANK_LAST_NAME,
    USER_BLANK_ROLE_ID,
    USER_BLANK_USER_ID,
    USER_CANNOT_CHANGE_EMAIL,
    USER_CANNOT_CHANGE_PASSWORD,
    USER_CANNOT_SET_ADMIN_ROLE,
    USER_CANNOT_UPDATE_ADMIN_ROLE,
    USER_EMAIL_EXISTS,
    USER_EMPTY_PASSWORD,
    USER_EMPTY_ROLE_DATA,
    USER_EMPTY_USER_DATA,
    USER_NO_PERMISSION_TO_CHANGE_PASSWORD,
    USER_NOT_FOUND

}
